/** Hebrew UI copy for the admin panel (Hebrew-only, no runtime i18n). */

export const adminCopy = {
  brand: {
    title: "Lev Ari",
    subtitle: "ניהול תוכן",
    loginBrand: "Lev Ari Productions",
    headerBadge: "ניהול Lev Ari",
    defaultPageTitle: "ניהול",
  },
  nav: {
    dashboard: "לוח בקרה",
    categories: "קטגוריות וידאו",
    videos: "סרטונים",
    stills: "גלריית תמונות",
    services: "שירותים",
    content: "תוכן האתר",
    leads: "פניות",
    integrations: "אינטגרציות",
  },
  search: {
    label: "חיפוש",
    placeholder: "חיפוש…",
    noResults: "לא נמצאו תוצאות לחיפוש.",
  },
  actions: {
    save: "שמירה",
    saving: "שומר…",
    cancel: "ביטול",
    delete: "מחיקה",
    deleting: "מוחק…",
    edit: "עריכה",
    add: "הוספה",
    close: "סגירה",
    view: "צפייה",
    viewAll: "הצג הכל",
    viewSite: "חזרה לאתר",
    copySiteLink: "העתקת קישור לאתר",
    linkCopied: "הקישור הועתק",
    copyLinkFailed: "לא ניתן להעתיק את הקישור",
    logout: "התנתקות",
    signingOut: "מתנתק…",
    menu: "תפריט",
    openMenu: "פתיחת תפריט",
    closeMenu: "סגירת תפריט",
    loading: "טוען…",
    signIn: "התחברות",
    signingIn: "מתחבר…",
    upload: "העלאה",
    uploading: "מעלה…",
    publishOnUpload: "פרסום עם ההעלאה",
    saveAllContent: "שמירת כל התוכן",
    none: "— ללא —",
  },
  publish: {
    published: "פעיל באתר",
    hidden: "מוסתר",
  },
  auth: {
    loginTitle: "כניסה לניהול",
    email: "אימייל",
    password: "סיסמה",
    invalidCredentials: "אימייל או סיסמה שגויים",
    accessDenied:
      "אין הרשאה לגשת למערכת הניהול. החשבון שלך אינו מורשה כמנהל.",
    accessDeniedShort: "אין הרשאה לגשת למערכת הניהול",
    emailPasswordRequired: "יש להזין אימייל וסיסמה.",
    somethingWrong: "משהו השתבש. נסו שוב.",
    signOutFailed: "לא ניתן להתנתק. נסו שוב.",
  },
  dashboard: {
    publishedVideos: "סרטונים מפורסמים",
    videoCategories: "קטגוריות וידאו",
    stillImages: "תמונות סטילס",
    services: "שירותים",
    leads: "פניות",
    quickLinks: "פעולות מהירות",
    addVideo: "הוספת סרטון",
    uploadStill: "העלאת תמונה",
    editHomepage: "עריכת תוכן האתר",
    recentLeads: "פניות אחרונות",
    noLeadsYet: "אין פניות עדיין.",
  },
  categories: {
    intro: "ניהול קטגוריות וידאו לתיק העבודות ולתצוגה באתר.",
    add: "הוספת קטגוריה",
    edit: "עריכת קטגוריה",
    new: "קטגוריה חדשה",
    titleEn: "כותרת באנגלית",
    titleHe: "כותרת בעברית",
    slug: "מזהה כתובת (Slug)",
    slugHint: "מזהה ייחודי לכתובת URL",
    initialVisible: "מספר פריטים ראשוני",
    sortOrder: "סדר הופעה",
    sortHint: "מספרים נמוכים יותר מוצגים קודם",
    emptyTitle: "לא נמצאו קטגוריות.",
    emptyDesc: "הוסיפו קטגוריית וידאו ראשונה לארגון העבודות.",
    created: "הקטגוריה נוצרה.",
    updated: "הקטגוריה עודכנה.",
    deleteTitle: "למחוק את הקטגוריה?",
    deleteMessage:
      "לא ניתן לבטל פעולה זו. לא ניתן למחוק קטגוריה שיש בה סרטונים — יש להעביר או למחוק את הסרטונים קודם.",
    tableTitle: "כותרת",
    tableTitleEn: "כותרת (EN)",
    tableSlug: "Slug",
    tableOrder: "סדר",
    tableVisible: "מוצגים",
    tableStatus: "סטטוס",
    tableActions: "פעולות",
  },
  videos: {
    intro: "ניהול סרטוני YouTube בתיק העבודות.",
    add: "הוספת סרטון",
    edit: "עריכת סרטון",
    new: "סרטון חדש",
    titleEn: "כותרת באנגלית",
    titleHe: "כותרת בעברית",
    category: "קטגוריה",
    youtubeUrl: "קישור YouTube",
    youtubeDetected: (id: string) => `מזהה שזוהה: ${id}`,
    youtubeHint: "הדביקו קישור YouTube תקין",
    youtubeInvalidInline:
      "קישור לא תקין — השתמשו ב-watch, youtu.be, embed או shorts.",
    customCover: "קאבר מותאם (אופציונלי)",
    emptyTitle: "אין סרטונים עדיין.",
    emptyDesc: "הוסיפו סרטון YouTube ראשון לתיק העבודות.",
    created: "הסרטון נוצר.",
    updated: "הסרטון נשמר בהצלחה.",
    deleteTitle: "למחוק את הסרטון?",
    deleteMessage: "הסרטון יוסר לצמיתות מתיק העבודות.",
    tablePreview: "תצוגה",
    tableTitle: "כותרת",
    tableCategory: "קטגוריה",
    noPreview: "אין תצוגה מקדימה",
  },
  stills: {
    collageLink: "עריכת קולאז׳",
    uploadTitle: "העלאת תמונות",
    uploadChoose: "בחר תמונות",
    uploadMultiHint: "ניתן לבחור כמה תמונות יחד",
    uploadProgress: (current: number, total: number) =>
      `מעלה ${current} מתוך ${total}`,
    uploadingMany: "מעלה תמונות…",
    uploadSummary: (ok: number, total: number) =>
      `הועלו ${ok} מתוך ${total} תמונות`,
    uploadFailedCount: (n: number) => `${n} תמונות נכשלו בהעלאה`,
    editTitle: "עריכת תמונה",
    altEn: "טקסט חלופי באנגלית",
    altHe: "טקסט חלופי בעברית",
    sortOrder: "סדר הופעה",
    emptyTitle: "לא הועלו תמונות עדיין.",
    emptyDesc:
      "העלו קבצי JPG, PNG או WebP. יחסי התמונה המקוריים נשמרים לגלריה.",
    uploaded: "התמונה הועלתה בהצלחה.",
    uploadedMany: (n: number) => `${n} תמונות הועלו בהצלחה.`,
    updated: "התמונה עודכנה.",
    dimensionsUnknown: "מידות לא ידועות",
    ratio: (n: number) => `יחס ${n.toFixed(2)}`,
    deleteTitle: "למחוק את התמונה?",
    deleteMessage: "הרשומה יימחקו מהמסד, וקובץ האחסון יוסר אם אפשר.",
    uploading: "מעלה תמונה…",
    uploadFailedHint: "בדקו את סוג הקובץ (JPG, PNG, WebP) וגודל (עד 10MB).",
  },
  services: {
    intro: "ניהול שירותים דו-לשוניים המוצגים באתר.",
    add: "הוספת שירות",
    edit: "עריכת שירות",
    new: "שירות חדש",
    titleEn: "כותרת באנגלית",
    titleHe: "כותרת בעברית",
    descEn: "תיאור באנגלית",
    descHe: "תיאור בעברית",
    iconKey: "מזהה אייקון",
    iconHint: "מזהה אופציונלי לאייקון בממשק הציבורי",
    emptyTitle: "לא נמצאו שירותים.",
    emptyDesc: "הוסיפו שירותים המוצגים בדף הבית.",
    created: "השירות נוצר.",
    updated: "השירות עודכן.",
    deleteTitle: "למחוק את השירות?",
    deleteMessage: "לא ניתן לבטל פעולה זו.",
    tableTitle: "כותרת",
    tableIcon: "אייקון",
  },
  content: {
    intro:
      "עריכת תוכן דו-לשוני ב-Supabase. כשערך ריק, האתר הציבורי משתמש בתרגומים המובנים.",
    saved:
      "תוכן האתר נשמר. האתר הציבורי ישתמש בערכי ה-CMS כשהם זמינים.",
    valueEn: "ערך באנגלית",
    valueHe: "ערך בעברית",
    sections: {
      hero: "אזור פתיחה",
      about: "אודות",
      works: "עבודות",
      services: "שירותים",
      contact: "צור קשר",
      seo: "SEO / קידום אורגני",
    } as Record<string, string>,
  },
  leads: {
    emptyTitle: "אין פניות עדיין.",
    emptyDesc: "פניות מטופס יצירת הקשר יופיעו כאן.",
    detailsTitle: "פרטי פנייה",
    name: "שם מלא",
    email: "אימייל",
    phone: "טלפון",
    service: "סוג שירות",
    message: "הודעה",
    language: "שפה",
    privacy: "אישור מדיניות פרטיות",
    submitted: "תאריך פנייה",
    yes: "כן",
    no: "לא",
    langHe: "עברית",
    langEn: "אנגלית",
    deleteTitle: "למחוק את הפנייה?",
    deleteMessage: "הפנייה תוסר לצמיתות.",
    tableName: "שם",
    tableEmail: "אימייל",
    tablePhone: "טלפון",
    tableService: "שירות",
    tableDate: "תאריך",
  },
  integrations: {
    title: "אינטגרציות",
    intro:
      "מצב משתני סביבה ובדיקות חיבור בטוחות. ערכי סודות אינם מוצגים.",
    envVars: "משתני סביבה",
    clientReady: "מוכנות לקוח",
    operational: "בדיקות מערכת",
    present: "קיים",
    missing: "חסר",
    footer:
      "בדיקת שליחת אימייל דרך טופס יצירת הקשר באתר (עברית ואנגלית). מדריך:",
    footerCmd: "npm run check:env",
    labels: {
      supabaseUrl: "כתובת Supabase מוגדרת",
      supabaseAnon: "מפתח anon של Supabase מוגדר",
      supabaseService: "מפתח service role של Supabase מוגדר",
      adminEmails: "ADMIN_ALLOWED_EMAILS מוגדר",
      resend: "מפתח Resend API מוגדר",
      emailFrom: "EMAIL_FROM מוגדר",
      contactEmail: "CONTACT_NOTIFICATION_EMAIL מוגדר",
      siteUrl: "כתובת האתר מוגדרת",
      publicClient: "ניתן להשתמש בלקוח Supabase הציבורי",
      adminClient: "ניתן להשתמש בלקוח admin (service role)",
      resendReady: "Resend מוכן (מפתח API + EMAIL_FROM)",
      readCategories: "ניתן לקרוא קטגוריות וידאו מפורסמות",
      readContent: "ניתן לקרוא תוכן אתר",
      currentAdmin: "משתמש מנהל נוכחי",
      isAdmin: "משתמש נוכחי הוא מנהל (DB או רשימת הרשאות)",
      stillsBucket: "גישה לדלי stills (מנהל)",
      notSignedIn: "לא מחובר",
      publishedCount: (n: number) => `(${n} מפורסמות)`,
      keysCount: (n: number) => `(${n} מפתחות)`,
    },
  },
  supabaseBanner: {
    title: "Supabase לא מוגדר",
    body: "הגדירו את NEXT_PUBLIC_SUPABASE_URL ו-NEXT_PUBLIC_SUPABASE_ANON_KEY בסביבה כדי להשתמש בלוח הניהול. כניסה וניהול תוכן דורשים פרויקט Supabase מחובר.",
  },
} as const;

/** Server-side validation and error messages shown in the admin UI. */
export const adminErrors = {
  supabaseNotConfigured:
    "Supabase לא מוגדר. הגדירו NEXT_PUBLIC_SUPABASE_URL ו-NEXT_PUBLIC_SUPABASE_ANON_KEY.",
  supabaseNotConfiguredShort: "Supabase לא מוגדר.",
  notSignedIn: "יש להתחבר כדי לבצע פעולה זו.",
  accessDenied: "אין הרשאה לגשת למערכת הניהול.",
  titleEnRequired: "כותרת באנגלית היא שדה חובה.",
  titleHeRequired: "כותרת בעברית היא שדה חובה.",
  slugRequired: "מזהה כתובת (Slug) הוא שדה חובה.",
  initialVisibleMin: "מספר הפריטים הראשוני חייב להיות לפחות 1.",
  youtubeRequired: "קישור YouTube הוא שדה חובה.",
  youtubeInvalid:
    "קישור YouTube לא תקין. השתמשו בקישור watch, youtu.be, embed או shorts.",
  youtubeParseFailed: "לא ניתן לזהות את מזהה סרטון YouTube.",
  categoryDeleteBlocked:
    "לא ניתן למחוק קטגוריה שיש בה סרטונים. יש להעביר או למחוק את הסרטונים קודם.",
  noImageFile: "לא נבחר קובץ תמונה.",
  invalidImageType: "סוג הקובץ לא נתמך",
  imageTooLarge: "הקובץ גדול מדי",
  stillUploadFailed: "העלאת התמונה נכשלה",
  uploadFailed: (msg: string) => `ההעלאה נכשלה: ${msg}`,
  storageDeleteFailed: (msg: string) => `לא ניתן למחוק מהאחסון: ${msg}`,
  saveContentFailed: (key: string, msg: string) =>
    `שמירת "${key}" נכשלה: ${msg}`,
  processUploadFailed: "עיבוד העלאת התמונה נכשל.",
  dimensionsUnreadable: "לא ניתן לקרוא את ממדי התמונה",
  storageUploadFailed: "העלאה ל־Storage נכשלה",
  dbInsertFailed: "שמירת התמונה במסד הנתונים נכשלה",
  invalidFileName: "שם הקובץ לא תקין",
  collageSaveFailed: "שמירת הפריסה נכשלה.",
  collageSaved: "הפריסה נשמרה בהצלחה.",
} as const;

export const adminPageTitles: Record<string, string> = {
  "/admin": adminCopy.nav.dashboard,
  "/admin/categories": adminCopy.nav.categories,
  "/admin/videos": adminCopy.nav.videos,
  "/admin/stills": adminCopy.nav.stills,
  "/admin/services": adminCopy.nav.services,
  "/admin/content": adminCopy.nav.content,
  "/admin/leads": adminCopy.nav.leads,
  "/admin/integrations": adminCopy.nav.integrations,
};

export function contentSectionTitle(title: string): string {
  return adminCopy.content.sections[title.toLowerCase()] ?? title;
}
